### ISSUE TITLE
Still getting Nulls in layout put

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/malcolmjs#443]
malcolm.core.request: Exception raised for request Put(id=990, path=Array([u'BL45P-ML-SCAN-01', u'layout', u'value']), value=ordereddict([(u'name', [None, u'MIC']), (u'visible', [False, False]), (u'mri', [u'BL45P-ML-PANDA-01:SEQ1', u'BL45P-ML-MIC-01']), (u'x', [0, 0]), (u'y', [0, 0])]), get=False)
Traceback (most recent call last):
  File "./malcolm/../malcolm/core/controller.py", line 141, in _handle_request
    responses += handler(request)
  File "./malcolm/../malcolm/core/controller.py", line 196, in _handle_put
    value = attribute.meta.validate(request.value)
  File "./malcolm/../malcolm/core/models.py", line 789, in validate
    args = {k: meta.validate(value[k]) for k, meta in self.elements.items()}
  File "./malcolm/../malcolm/core/models.py", line 789, in <dictcomp>
    args = {k: meta.validate(value[k]) for k, meta in self.elements.items()}
  File "./malcolm/../malcolm/core/models.py", line 694, in validate
    assert isinstance(v, str_), "Expected Array[str], got %r" % (value,)
AssertionError: Expected Array[str], got [None, u'MIC']

**Comment by thomascobb** [comment]
Looks like it's triggered after transitioning from a SCAN block into a PANDA
